// frontend/angular-app/src/app/features/auth/login/login.component.ts
import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { HttpErrorResponse } from '@angular/common/http';
import { AuthService } from '../../../core/services/auth.service';
import { ToastService } from '../../../core/services/toast.service';
import { FieldErrorComponent } from '../../../shared/components/field-error.component';
import { ProblemResponse } from '../../../core/models/models';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink, FieldErrorComponent],
  template: `
    <div class="space-y-8">
      <div>
        <h2 class="text-2xl font-bold text-slate-900 tracking-tight">Bem-vindo de volta</h2>
        <p class="mt-1 text-sm text-slate-500">Acesse sua conta para continuar.</p>
      </div>

      <form [formGroup]="form" (ngSubmit)="submit()" novalidate class="space-y-5">

        <div class="space-y-1">
          <label for="l-email" class="block text-sm font-medium text-slate-700">E-mail</label>
          <input id="l-email" type="email" formControlName="email" autocomplete="email"
                 placeholder="voce@email.com"
                 class="w-full rounded-lg border px-3.5 py-2.5 text-sm outline-none transition-all
                        focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                 [class]="fc('email')" [attr.aria-invalid]="inv('email')" />
          <app-field-error [message]="emailErr()" />
        </div>

        <div class="space-y-1">
          <label for="l-pass" class="block text-sm font-medium text-slate-700">Senha</label>
          <div class="relative">
            <input id="l-pass" [type]="showPwd() ? 'text' : 'password'"
                   formControlName="password" autocomplete="current-password"
                   placeholder="••••••••"
                   class="w-full rounded-lg border px-3.5 py-2.5 pr-10 text-sm outline-none transition-all
                          focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                   [class]="fc('password')" [attr.aria-invalid]="inv('password')" />
            <button type="button" (click)="showPwd.set(!showPwd())"
                    class="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
                    [attr.aria-label]="showPwd() ? 'Ocultar senha' : 'Mostrar senha'">
              {{ showPwd() ? '🙈' : '👁' }}
            </button>
          </div>
          <app-field-error [message]="passErr()" />
        </div>

        @if (apiErr()) {
          <div role="alert" class="rounded-lg bg-red-50 border border-red-200 px-4 py-3
                                    text-sm text-red-700 flex items-start gap-2">
            <span aria-hidden="true" class="mt-0.5">⚠</span><span>{{ apiErr() }}</span>
          </div>
        }

        <button type="submit" [disabled]="loading()"
                class="w-full rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white
                       hover:bg-indigo-700 disabled:opacity-60 disabled:cursor-not-allowed transition-all">
          @if (loading()) {
            <span class="flex items-center justify-center gap-2">
              <svg class="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
              </svg>Entrando…
            </span>
          } @else { Entrar }
        </button>
      </form>

      <p class="text-center text-sm text-slate-500">
        Não tem conta?
        <a routerLink="/auth/register" class="font-semibold text-indigo-600 hover:text-indigo-500">Criar conta</a>
      </p>
    </div>
  `,
})
export class LoginComponent implements OnInit {
  private readonly fb    = inject(FormBuilder);
  private readonly auth  = inject(AuthService);
  private readonly toast = inject(ToastService);
  private readonly router = inject(Router);

  readonly loading = signal(false);
  readonly apiErr  = signal<string | null>(null);
  readonly showPwd = signal(false);

  form = this.fb.nonNullable.group({
    email:    ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required]],
  });

  readonly emailErr = computed(() => {
    const c = this.form.controls.email;
    if (!c.invalid || !c.touched) return null;
    return c.hasError('required') ? 'E-mail obrigatório.' : 'E-mail inválido.';
  });

  readonly passErr = computed(() => {
    const c = this.form.controls.password;
    return c.invalid && c.touched ? 'Senha obrigatória.' : null;
  });

  ngOnInit() { if (this.auth.isAuthenticated()) this.router.navigate(['/developers']); }

  inv(f: 'email' | 'password') { const c = this.form.controls[f]; return c.invalid && c.touched; }
  fc(f: 'email' | 'password')  {
    return this.inv(f) ? 'border-red-400 bg-red-50' : 'border-slate-300 bg-white hover:border-slate-400';
  }

  submit() {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    this.loading.set(true); this.apiErr.set(null);
    const { email, password } = this.form.getRawValue();
    this.auth.login({ email, password }).subscribe({
      next: () => { this.toast.success('Login realizado!'); this.router.navigate(['/developers']); },
      error: (e: HttpErrorResponse) => {
        this.loading.set(false);
        if (e.status === 0) { this.apiErr.set('Servidor indisponível.'); return; }
        this.apiErr.set((e.error as ProblemResponse)?.detail ?? 'E-mail ou senha inválidos.');
      },
    });
  }
}

// frontend/next-app/src/app/auth/login/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Eye, EyeOff } from 'lucide-react';
import { useAuth } from '@/lib/hooks/use-auth';
import { loginSchema, LoginFormValues } from '@/lib/schemas';
import { handleError } from '@/lib/hooks/use-crud';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Card, CardContent, CardDescription, CardHeader, CardTitle,
} from '@/components/ui/card';

export default function LoginPage() {
  const { login }          = useAuth();
  const [loading, setL]    = useState(false);
  const [showPwd, setShow] = useState(false);

  const {
    register, handleSubmit, formState: { errors },
  } = useForm<LoginFormValues>({ resolver: zodResolver(loginSchema) });

  const onSubmit = async (values: LoginFormValues) => {
    setL(true);
    try {
      await login(values.email, values.password);
    } catch (err) {
      handleError(err, 'E-mail ou senha inválidos.');
    } finally {
      setL(false);
    }
  };

  return (
    
    <div className="min-h-screen flex bg-background">

      <aside
        aria-hidden="true"
        className="hidden lg:flex lg:w-2/5 flex-col justify-between
                   bg-slate-900 px-12 py-14 text-white relative overflow-hidden"
      >
        <div
          className="absolute inset-0 opacity-[0.04] pointer-events-none"
          style={{
            backgroundImage:
              'linear-gradient(#fff 1px,transparent 1px),linear-gradient(90deg,#fff 1px,transparent 1px)',
            backgroundSize: '32px 32px',
          }}
        />
        <div className="absolute -top-24 -left-24 w-96 h-96 rounded-full
                        bg-indigo-600 opacity-20 blur-3xl pointer-events-none" />

        <div className="relative z-10 flex items-center gap-3">
          <span className="w-9 h-9 rounded-lg bg-indigo-500 flex items-center
                           justify-center text-white font-bold text-sm shrink-0">
            DS
          </span>
          <span className="text-base font-semibold tracking-tight">DevStackManager</span>
        </div>

        <div className="relative z-10 space-y-4">
          <h1 className="text-4xl font-bold leading-tight">
            Gerencie seu time de<br />
            <span className="text-indigo-400">desenvolvedores</span><br />
            com precisão.
          </h1>
          <p className="text-slate-400 text-sm max-w-xs leading-relaxed">
            Centralize senioridades, linguagens e localizações numa
            plataforma feita para equipes de engenharia.
          </p>
        </div>

        <p className="relative z-10 text-slate-600 text-xs">
          &copy; {new Date().getFullYear()} DevStackManager
        </p>
      </aside>

      <main className="flex-1 flex flex-col items-center justify-center
                       bg-background px-6 py-12 sm:px-10">

        <div className="lg:hidden mb-8 flex items-center gap-2">
          <span className="w-8 h-8 rounded-lg bg-primary flex items-center
                           justify-center text-primary-foreground font-bold text-sm">
            DS
          </span>
          <span className="font-semibold text-foreground">DevStackManager</span>
        </div>

        <Card className="w-full max-w-md shadow-lg border-border">
          <CardHeader className="space-y-1">
            <CardTitle className="text-2xl text-foreground">Bem-vindo de volta</CardTitle>
            <CardDescription className="text-muted-foreground">
              Acesse sua conta para continuar.
            </CardDescription>
          </CardHeader>

          <CardContent>
            <form onSubmit={handleSubmit(onSubmit)} noValidate className="space-y-4">

              <div className="space-y-1.5">
                <Label htmlFor="login-email" className="text-foreground">E-mail</Label>
                <Input
                  id="login-email"
                  type="email"
                  autoComplete="email"
                  placeholder="voce@email.com"
                  className={errors.email
                    ? 'border-destructive focus-visible:ring-destructive'
                    : ''}
                  {...register('email')}
                  aria-invalid={!!errors.email}
                  aria-describedby={errors.email ? 'email-error' : undefined}
                />
                {errors.email && (
                  <p id="email-error" className="text-xs text-destructive" role="alert">
                    {errors.email.message}
                  </p>
                )}
              </div>

              <div className="space-y-1.5">
                <Label htmlFor="login-password" className="text-foreground">Senha</Label>
                <div className="relative">
                  <Input
                    id="login-password"
                    type={showPwd ? 'text' : 'password'}
                    autoComplete="current-password"
                    placeholder="••••••••"
                    className={`pr-10 ${errors.password
                      ? 'border-destructive focus-visible:ring-destructive'
                      : ''}`}
                    {...register('password')}
                    aria-invalid={!!errors.password}
                    aria-describedby={errors.password ? 'password-error' : undefined}
                  />
                  <button
                    type="button"
                    onClick={() => setShow(v => !v)}
                    className="absolute right-3 top-1/2 -translate-y-1/2
                               text-muted-foreground hover:text-foreground
                               transition-colors"
                    aria-label={showPwd ? 'Ocultar senha' : 'Mostrar senha'}
                  >
                    {showPwd
                      ? <EyeOff className="h-4 w-4" />
                      : <Eye    className="h-4 w-4" />}
                  </button>
                </div>
                {errors.password && (
                  <p id="password-error" className="text-xs text-destructive" role="alert">
                    {errors.password.message}
                  </p>
                )}
              </div>

              <Button type="submit" className="w-full" disabled={loading}>
                {loading
                  ? <span className="flex items-center gap-2">
                      <span className="h-4 w-4 animate-spin rounded-full
                                       border-2 border-current border-t-transparent" />
                      Entrando…
                    </span>
                  : 'Entrar'}
              </Button>
            </form>

            <p className="mt-5 text-center text-sm text-muted-foreground">
              Não tem conta?{' '}
              <Link
                href="/auth/register"
                className="font-semibold text-primary hover:text-primary/80
                           underline-offset-4 hover:underline transition-colors"
              >
                Criar conta
              </Link>
            </p>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
